spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    generate-unique-name: false #??? ?? 2.3?? ???? DB? ?? ??? ???? ??? ??? ?????. ?? ????? ?? testdb? ????? ?? ??? application.properties? ???? ??.
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none

mybatis:
  configuration:
    cache-enabled: true                             # ???? ? ??? ??? ??? ????? ???? ??? ?? ??
    lazy-loading-enabled: true                      # ????? ????? ?? ??
    multiple-result-sets-enabled: true              # ??? ???? ???? ResultSet? ???? ??
    use-column-label: true                          # ??? ??? ????? ??
    use-generated-keys: false                       # ???? ?? JDBC ??? ?
    auto-mapping-behavior: partial                  # Mybatis? ??? ??/????? ???? ????? ??? ?? ??
    auto-mapping-unknown-column-behavior: warning   # ???? ??? ?? ?? ??? ????? ??? ??
    default-executor-type: simple                   # default ??? ??
    default-statement-timeout: 30                   # ???????? ??? ??? ?? ???? ???? ????? ??
    default-fetch-size: 100                         # ????? ???? ??? ??? ??? ???? ??
    safe-row-bounds-enabled: false                  # ????? RowBound ??? ??
    map-underscore-to-camel-case: true              # ???? ?????? ??? ??? A_COLUMN? CamelCase??? ??
    local-cache-scope: session                      # Mybatis? ????? ??? ??? ??? ??? ??? ?? ????? ??
    jdbc-type-for-null: other                       # JDBC??? ????? ???? ??? null?? ??? JDBC??? ??
    lazy-load-trigger-methods:                      # ????? ???? ??? ???? ??
      - equals
      - clone
      - hashCode
      - toString
    call-setters-on-nulls: true                     # ??? ?? null?? setter? ?? put ???? ????? ??
  mapper-locations: classpath:mapper/**/*.xml

